/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AssociationInfo;
import io.swagger.client.model.ContentInfo;
import io.swagger.client.model.Definition;
import io.swagger.client.model.Node;
import io.swagger.client.model.PathInfo;
import io.swagger.client.model.PermissionsInfo;
import io.swagger.client.model.UserInfo;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * NodeAssociation
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-04T08:19:38.842344610Z[GMT]")

public class NodeAssociation extends Node {
  @SerializedName("association")
  private AssociationInfo association = null;

  public NodeAssociation association(AssociationInfo association) {
    this.association = association;
    return this;
  }

   /**
   * Get association
   * @return association
  **/
  @Schema(description = "")
  public AssociationInfo getAssociation() {
    return association;
  }

  public void setAssociation(AssociationInfo association) {
    this.association = association;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeAssociation nodeAssociation = (NodeAssociation) o;
    return Objects.equals(this.association, nodeAssociation.association) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(association, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeAssociation {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    association: ").append(toIndentedString(association)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
