/*
 * Alfresco Content Services REST API
 * **Core API**  Provides access to the core features of Alfresco Content Services. 
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Constraint;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Property
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-03-04T08:19:38.842344610Z[GMT]")

public class Property {
  @SerializedName("id")
  private String id = null;

  @SerializedName("title")
  private String title = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("defaultValue")
  private String defaultValue = null;

  @SerializedName("dataType")
  private String dataType = null;

  @SerializedName("isMultiValued")
  private Boolean isMultiValued = null;

  @SerializedName("isMandatory")
  private Boolean isMandatory = null;

  @SerializedName("isMandatoryEnforced")
  private Boolean isMandatoryEnforced = null;

  @SerializedName("isProtected")
  private Boolean isProtected = null;

  @SerializedName("constraints")
  private List<Constraint> constraints = null;

  public Property id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Property title(String title) {
    this.title = title;
    return this;
  }

   /**
   * the human-readable title
   * @return title
  **/
  @Schema(description = "the human-readable title")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Property description(String description) {
    this.description = description;
    return this;
  }

   /**
   * the human-readable description
   * @return description
  **/
  @Schema(description = "the human-readable description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Property defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * the default value
   * @return defaultValue
  **/
  @Schema(description = "the default value")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public Property dataType(String dataType) {
    this.dataType = dataType;
    return this;
  }

   /**
   * the name of the property type (e.g. d:text)
   * @return dataType
  **/
  @Schema(description = "the name of the property type (e.g. d:text)")
  public String getDataType() {
    return dataType;
  }

  public void setDataType(String dataType) {
    this.dataType = dataType;
  }

  public Property isMultiValued(Boolean isMultiValued) {
    this.isMultiValued = isMultiValued;
    return this;
  }

   /**
   * define if the property is multi-valued
   * @return isMultiValued
  **/
  @Schema(description = "define if the property is multi-valued")
  public Boolean isIsMultiValued() {
    return isMultiValued;
  }

  public void setIsMultiValued(Boolean isMultiValued) {
    this.isMultiValued = isMultiValued;
  }

  public Property isMandatory(Boolean isMandatory) {
    this.isMandatory = isMandatory;
    return this;
  }

   /**
   * define if the property is mandatory
   * @return isMandatory
  **/
  @Schema(description = "define if the property is mandatory")
  public Boolean isIsMandatory() {
    return isMandatory;
  }

  public void setIsMandatory(Boolean isMandatory) {
    this.isMandatory = isMandatory;
  }

  public Property isMandatoryEnforced(Boolean isMandatoryEnforced) {
    this.isMandatoryEnforced = isMandatoryEnforced;
    return this;
  }

   /**
   * define if the presence of mandatory properties is enforced
   * @return isMandatoryEnforced
  **/
  @Schema(description = "define if the presence of mandatory properties is enforced")
  public Boolean isIsMandatoryEnforced() {
    return isMandatoryEnforced;
  }

  public void setIsMandatoryEnforced(Boolean isMandatoryEnforced) {
    this.isMandatoryEnforced = isMandatoryEnforced;
  }

  public Property isProtected(Boolean isProtected) {
    this.isProtected = isProtected;
    return this;
  }

   /**
   * define if the property is system maintained
   * @return isProtected
  **/
  @Schema(description = "define if the property is system maintained")
  public Boolean isIsProtected() {
    return isProtected;
  }

  public void setIsProtected(Boolean isProtected) {
    this.isProtected = isProtected;
  }

  public Property constraints(List<Constraint> constraints) {
    this.constraints = constraints;
    return this;
  }

  public Property addConstraintsItem(Constraint constraintsItem) {
    if (this.constraints == null) {
      this.constraints = new ArrayList<Constraint>();
    }
    this.constraints.add(constraintsItem);
    return this;
  }

   /**
   * list of constraints defined for the property
   * @return constraints
  **/
  @Schema(description = "list of constraints defined for the property")
  public List<Constraint> getConstraints() {
    return constraints;
  }

  public void setConstraints(List<Constraint> constraints) {
    this.constraints = constraints;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Property property = (Property) o;
    return Objects.equals(this.id, property.id) &&
        Objects.equals(this.title, property.title) &&
        Objects.equals(this.description, property.description) &&
        Objects.equals(this.defaultValue, property.defaultValue) &&
        Objects.equals(this.dataType, property.dataType) &&
        Objects.equals(this.isMultiValued, property.isMultiValued) &&
        Objects.equals(this.isMandatory, property.isMandatory) &&
        Objects.equals(this.isMandatoryEnforced, property.isMandatoryEnforced) &&
        Objects.equals(this.isProtected, property.isProtected) &&
        Objects.equals(this.constraints, property.constraints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, defaultValue, dataType, isMultiValued, isMandatory, isMandatoryEnforced, isProtected, constraints);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Property {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    dataType: ").append(toIndentedString(dataType)).append("\n");
    sb.append("    isMultiValued: ").append(toIndentedString(isMultiValued)).append("\n");
    sb.append("    isMandatory: ").append(toIndentedString(isMandatory)).append("\n");
    sb.append("    isMandatoryEnforced: ").append(toIndentedString(isMandatoryEnforced)).append("\n");
    sb.append("    isProtected: ").append(toIndentedString(isProtected)).append("\n");
    sb.append("    constraints: ").append(toIndentedString(constraints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
